#! /usr/bin/env python
import os
import pathlib
import sys

import typer

# Setup sys path ---
project_dir = os.path.dirname(os.path.dirname(__file__))
sys.path.append(project_dir)
# ---

from src.students.db.setup import setup_db
from src.students.db.connection import connection

app = typer.Typer()


@app.command()
def setup():
    """Sets up the DB for running the script."""
    setup_db()


@app.command()
def seed():
    """Sets up the mock data in the DB. You can change the seed data in seed.sql"""
    seed_file_path = pathlib.Path(project_dir) / 'seed/seed.sql'
    with open(seed_file_path, 'r') as f:
        sql = f.read()

    connection.execute(sql)
    connection.commit()


if __name__ == '__main__':
    app()
