#! /usr/bin/env python
import os
import sys
from pprint import pprint
from typing import Optional

import typer

# Setup sys path ---
project_dir = os.path.dirname(os.path.dirname(__file__))
sys.path.append(project_dir)
# ---

from src.students.student_marks import get_top_n_highest_scorers


def main(n: Optional[int] = typer.Option(3, "--num-students", "-n", help="Number of top students to fetch")):
    """Gets the top 3 students sorted by their sum of total marks."""
    rows = get_top_n_highest_scorers(n=n)
    pprint(rows)


if __name__ == '__main__':
    typer.run(main)
