#! /usr/bin/env python
import os
import sys
from typing import List

import typer

# Setup sys path ---
project_dir = os.path.dirname(os.path.dirname(__file__))
sys.path.append(project_dir)
# ---

from src.number_sorter import sort


def main(numbers: List[int],
         start_place_value_exp: int = typer.Option(..., "--start-digit", "-s"),
         end_place_value_exp: int = typer.Option(..., "--end-digit", "-e")):
    res = sort(numbers, start_place_value_exp - 1, end_place_value_exp - 1)
    print("---------------------")
    print(f"Sorted List: {res}")


if __name__ == '__main__':
    typer.run(main)
